export async function GET() {
    return Response.json({
        success: true,
        message: "Products retrieved successfully",
        data: [
            {
                id: 1,
                name: "Waterproof Shower Head",
                categoryId: 1,
                categoryType: "bathroom",
                description: "High-pressure shower head with multiple settings.",
                price: 20.99,
                stockQuantity: 100,
                waterproof: true,
                installationType: "wall-mounted"
            },
            {
                id: 2,
                name: "Anti-Fog Bathroom Mirror",
                categoryId: 1,
                categoryType: "bathroom",
                description: "Heated mirror with anti-fog technology.",
                price: 45.99,
                stockQuantity: 80,
                waterproof: true,
                installationType: "wall-mounted"
            },
            {
                id: 3,
                name: "Luxury Bathtub",
                categoryId: 1,
                categoryType: "bathroom",
                description: "Freestanding bathtub with modern design.",
                price: 799.99,
                stockQuantity: 20,
                waterproof: true,
                installationType: "freestanding"
            },
            {
                id: 4,
                name: "Toilet Paper Holder",
                categoryId: 1,
                categoryType: "bathroom",
                description: "Wall-mounted toilet paper holder with storage shelf.",
                price: 15.99,
                stockQuantity: 150,
                waterproof: false,
                installationType: "wall-mounted"
            },
            {
                id: 5,
                name: "Ergonomic Office Chair",
                categoryId: 2,
                categoryType: "furniture",
                description: "Comfortable office chair with adjustable height and lumbar support.",
                price: 150.00,
                stockQuantity: 50,
                material: "Mesh and Metal",
                weightCapacity: 250,
                dimensions: { width: 24, height: 40, depth: 24 }
            },
            {
                id: 6,
                name: "Convertible Sofa Bed",
                categoryId: 2,
                categoryType: "furniture",
                description: "Stylish sofa that converts into a comfortable bed.",
                price: 299.99,
                stockQuantity: 30,
                material: "Fabric and Wood",
                weightCapacity: 500,
                dimensions: { width: 80, height: 35, depth: 40 }
            },
            {
                id: 7,
                name: "Wooden Dining Table",
                categoryId: 2,
                categoryType: "furniture",
                description: "Solid wood dining table with seating for six.",
                price: 499.99,
                stockQuantity: 25,
                material: "Oak Wood",
                weightCapacity: 800,
                dimensions: { width: 72, height: 30, depth: 36 }
            },
            {
                id: 8,
                name: "Bookshelf",
                categoryId: 2,
                categoryType: "furniture",
                description: "Tall bookshelf with five adjustable shelves.",
                price: 120.00,
                stockQuantity: 40,
                material: "Engineered Wood",
                weightCapacity: 100,
                dimensions: { width: 30, height: 72, depth: 12 }
            },
            // garden products
            {
                id: 9,
                name: "Indoor Herb Garden Kit",
                categoryId: 3,
                categoryType: "garden",
                description: "Complete kit for growing herbs indoors.",
                price: 35.99,
                stockQuantity: 200,
                plantType: "Herbs",
                requiresSunlight: true
            },
            {
                id: 10,
                name: "Solar Garden Lights",
                categoryId: 3,
                categoryType: "garden",
                description: "Set of 8 solar-powered lights for outdoor use.",
                price: 29.99,
                stockQuantity: 120,
                plantType: null,
                requiresSunlight: true
            },
            {
                id: 11,
                name: "Garden Hose",
                categoryId: 3,
                categoryType: "garden",
                description: "Flexible and durable garden hose with spray nozzle.",
                price: 25.99,
                stockQuantity: 100,
                plantType: null,
                requiresSunlight: false
            },
            {
                id: 12,
                name: "Compost Bin",
                categoryId: 3,
                categoryType: "garden",
                description: "Outdoor compost bin for organic waste.",
                price: 49.99,
                stockQuantity: 60,
                plantType: null,
                requiresSunlight: false
            },
            {
                id: 13,
                name: "LED Desk Lamp",
                categoryId: 4,
                categoryType: "lamp",
                description: "Energy-efficient LED desk lamp with adjustable brightness.",
                price: 25.99,
                stockQuantity: 150,
                wattage: 10,
            },
            {
                id: 14,
                name: "Smart Floor Lamp",
                categoryId: 4,
                categoryType: "lamp",
                description: "Voice-controlled floor lamp with adjustable color temperature.",
                price: 89.99,
                stockQuantity: 60,
                wattage: 15,
            },
            {
                id: 15,
                name: "Vintage Table Lamp",
                categoryId: 4,
                categoryType: "lamp",
                description: "Classic table lamp with a vintage design.",
                price: 45.99,
                stockQuantity: 80,
                wattage: 40,
            },
            {
                id: 16,
                name: "Outdoor Wall Lantern",
                categoryId: 4,
                categoryType: "lamp",
                description: "Weather-resistant wall lantern for outdoor lighting.",
                price: 59.99,
                stockQuantity: 70,
                wattage: 60,
            }
        ],
    });
}