describe('Product Page', () => {
    it('Test Drawer', () => {
        cy.visit('https://home24-frontend.vercel.app')
        cy.get('#basic_username').type('admin')
        cy.get('#basic_password').type('123')
        cy.get('.ant-btn').click({ force: true })
        cy.wait(3000)
        cy.get('[data-row-key="1"]').click({ force: true })
        cy.wait(1000)
        cy.get('.ant-space > :nth-child(2) > .ant-btn').click({ force: true })
    })

    it('Test Drawer Sorting | Asc | Desc', () => {
        cy.visit('https://home24-frontend.vercel.app')
        cy.get('#basic_username').type('admin')
        cy.get('#basic_password').type('123')
        cy.get('.ant-btn').click({ force: true })
        cy.wait(3000)
        cy.contains('Product name').click({ force: true })
        cy.wait(1000)
        cy.contains('Product name').click({ force: true })
    })

    it('Test Drawer Sorting | Asc | Desc', () => {
        cy.visit('https://home24-frontend.vercel.app')
        cy.get('#basic_username').type('admin')
        cy.get('#basic_password').type('123')
        cy.get('.ant-btn').click({ force: true })
        cy.wait(3000)
        cy.contains('Product name').click({ force: true })
        cy.wait(1000)
        cy.contains('Product name').click({ force: true })
    })

    it('Category List Test', () => {
        cy.visit('https://home24-frontend.vercel.app')
        cy.get('#basic_username').type('admin')
        cy.get('#basic_password').type('123')
        cy.get('.ant-btn').click({ force: true })
        cy.wait(3000)
        cy.contains('Seating').trigger('mouseover')
        cy.wait(1000)
        cy.contains('Chairs').trigger('mouseover')
        cy.wait(1000)
        cy.get('.ant-layout-sider-children > .flex').trigger('mouseover')
    })
})